#!/usr/bin/env python3

"""==============================================================================
MSX .CAS to .WAV Converter Engine
Adapted via Gemini (Google) on July 5, 2026.

Technical Specifications Derived From:
- MSX Assembly Page: Tape Data Structure Spec (1200/2400Hz FSK Hardware Layer)
- CAS File Format Definition (8-byte header token: 1F A6 DE BA CC 13 7D 74)
==============================================================================

The code provided in this file is entirely public domain, meaning you are
legally free to do whatever you want with it. Because it was generated by an AI
assistant based on public, historical technical specifications, it is not
bound by any pre-existing software license.

## Acknowledgments
* **MSX Technical Specifications:** Data protocol rules based on the original
  MSX 1 Hardware BIOS specification for Frequency Shift Keying (FSK) cassette
  modulation.
* **Implementation Engine:** Code structure and cycle-exact sample synthesis
  generated in collaboration with Google AI Search (July 2026).
"""

import argparse
import base64
import lzma
import math
import os
import struct
import sys
import tempfile
import wave

CAS_HEADER_MARKER = b"\x1f\xa6\xde\xba\xcc\x13\x7d\x74"
SAMPLE_RATE = 22050
PEAK_AMPLITUDE = 0.7
FIRST_LEADER_DURATION = 4.0
NORMAL_LEADER_DURATION = 2.0
FINAL_SILENCE_DURATION = 2.0
BAUD_RATE = 1200


def generate_cycle(freq):
    samples_in_cycle = int(SAMPLE_RATE / freq)
    cycle = []
    for i in range(samples_in_cycle):
        value = PEAK_AMPLITUDE * math.sin(2 * math.pi * (i / samples_in_cycle))
        cycle.append(int(value * 32767.0))
    return cycle


def generate_silence(duration):
    samples_in_silence = int(SAMPLE_RATE * duration)
    return [0] * samples_in_silence


def encode_bit(bit_value):
    samples = []
    if bit_value == 0:
        samples.extend(generate_cycle(BAUD_RATE))
    else:
        samples.extend(generate_cycle(2 * BAUD_RATE))
        samples.extend(generate_cycle(2 * BAUD_RATE))
    return samples


def encode_byte(byte_val):
    samples = []
    samples.extend(encode_bit(0))
    for i in range(8):
        bit = (byte_val >> i) & 1
        samples.extend(encode_bit(bit))
    samples.extend(encode_bit(1))
    samples.extend(encode_bit(1))
    return samples


def generate_pilot_leader(duration_seconds):
    samples = []
    cycles_needed = int(2 * BAUD_RATE * duration_seconds)
    for _ in range(cycles_needed):
        samples.extend(generate_cycle(2 * BAUD_RATE))
    return samples


def cas_to_wav(cas_filename, wav_filename):
    # this is a general purpose data converter. the extension
    # validation by assertion is reasonable, but dictating other
    # aspects of the input and output paths would not be, so we
    # suppress sonarqube validation/taint analysis
    assert os.path.splitext(cas_filename)[-1].lower() == ".cas"
    assert os.path.splitext(wav_filename)[-1].lower() == ".wav"
    with open(cas_filename, "rb") as f:  # NOSONAR
        cas_data = f.read()
    pcm_frames = []
    idx = 0
    total_bytes = len(cas_data)
    prev_leader_was_long = None
    current_block_bytes = 0
    while idx < total_bytes:
        if cas_data[idx : idx + 8] == CAS_HEADER_MARKER:
            if prev_leader_was_long is None:
                leader_is_long = True
            elif prev_leader_was_long and current_block_bytes == 16:
                leader_is_long = False
            else:
                leader_is_long = True
            leader_duration = (
                FIRST_LEADER_DURATION if leader_is_long else NORMAL_LEADER_DURATION
            )
            pcm_frames.extend(generate_pilot_leader(leader_duration))
            prev_leader_was_long = leader_is_long
            current_block_bytes = 0
            idx += 8
        else:
            pcm_frames.extend(encode_byte(cas_data[idx]))
            current_block_bytes += 1
            idx += 1
    pcm_frames.extend(generate_silence(FINAL_SILENCE_DURATION))
    with wave.open(wav_filename, "wb") as wav_file:  # NOSONAR
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(SAMPLE_RATE)
        packed_data = struct.pack(f"{len(pcm_frames)}h", *pcm_frames)
        wav_file.writeframes(packed_data)


def run_self_tests():
    # test 1: single-block encoding
    # this WAV was generated and encoded by:
    # ```bash
    # LC_ALL=C printf '\x1f\xa6\xde\xba\xcc\x13\x7d\x74%s' TEST > test.cas &&
    #     python3 cas2wav.py test.cas test.wav &&
    #     lzma -9 < test.wav | recode l1..l1/b64
    # ```
    expected_wav_single = lzma.decompress(
        base64.b64decode(
            "XQAAAAT//////////wApEkTrmN6NWD9/VTXn4ecOY4FtT/55rcJhTYtnpJCd4o6aYb7RT"
            "0LxXkXneXkXdZsVx3Y2qc66oczkz6UyaM5IWk9BKZhm+OBqFKV+D0txo48GT9zniR2UxYD"
            "vOBBxDFxj2A9HcutnvsNI9xkHHnLrtIStSTt+FVNDooHcDhNSB+jp5vOCIwiriVOwEjLd"
            "6gTJqK9WzqK1+bGapwXeFYlB3hCkARratbya1H/bNy2SHnF14rcKm0n4nJ1Zdv3LGRoQI4"
            "Fmv+0q7rxZUVprFnw7oIUs4qv23CaO2eTG1kOfZXK9Ut/G41lfBUEe+4JokA=="
        )
    )

    # test 2: multi-block pilot leader durations (heuristic rules)
    # this WAV was generated and encoded by:
    # ```bash
    # H='\x1f\xa6\xde\xba\xcc\x13\x7d\x74'
    # LC_ALL=C printf "${H}%s${H}%s${H}%s${H}%s" \
    #     0123456789ABCDEF 0123456789ABCDEF 0123456789 END > test.cas && \
    #     python3 cas2wav.py test.cas test.wav && \
    #     lzma -9 < test.wav | recode l1..l1/b64
    # ```
    expected_wav_multi = lzma.decompress(
        base64.b64decode(
            "XQAAAAT//////////wApEkTrg2pYp1otM4++17Ni59xlSAUj4kIUE3DoTXXVbjMnQd7g0Fp4tYmu"
            "W2NfMBkAmb9nPzpDO+W4mZoiV9/R5kXhwi8hzB50Vi0PH1P8tdvtpNsg2pa5ufCxV+V5gHeYNbBt"
            "LHp9orM4cpCWqK6KNRHNYvTIUg1gN8pZY88LvFvjB28BL2BhwsxiECybrXnNSZnA29uwcDXP25cb"
            "3+gaLlz4Dr1aWBODNbCzyIwC8XEauHVYQbTwIT0o152FXA1RiFjTFaHNke3I6BCTSlnKpMGHsdjD"
            "cz4B0vIBUgX3TgJlIclnRfyblYTHgCxpUJkaqjbw/m/JN21RUDCs4dr2faq9+KZiI85YzHc211rV"
            "CPluGbP1j8S6Dg3ktBpZKvpJ7TPAg3GyAmdIKq1Uw+bed61GvzP/hHHeCbvuMJLaIdVd2KHSfp1y"
            "d229LtMKtnCujq2sL6u42wRV3FGjWVUZx+6IEnfMKHnr7kyH4FgrxV5Roue71Xjl9AF92TTxEbkM"
            "wdIfMTlrJIGii1z2q+aEHzsVCSxJ6qC2JfVxaaUR9sWCL+L2GKI9kTw3cboDPUvn4ABd68ptiDMv"
            "DTVJyysvrYvnu9V45fQBfdydwAaYTZLIcvLt5vBayrXPsSYTGO5DefMI7IHjg8SQrsn7Ak7bf9C2"
            "rhv8nrqBDHHPKG4dPMbD+QMlfHryr3sd"
        )
    )

    passed = failed = 0

    with tempfile.TemporaryDirectory() as tmpdir:
        cas_path = os.path.join(tmpdir, "test1.cas")
        wav_path = os.path.join(tmpdir, "test1.wav")
        with open(cas_path, "wb") as f:
            f.write(CAS_HEADER_MARKER + b"TEST")
        cas_to_wav(cas_path, wav_path)
        with open(wav_path, "rb") as f:
            gen1 = f.read()
    ok1 = gen1 == expected_wav_single
    print("[%s] WAV encoding (single-block)" % ("PASS" if ok1 else "FAIL"))
    if ok1:
        passed += 1
    else:
        failed += 1

    multi_cas = (
        CAS_HEADER_MARKER
        + b"0123456789ABCDEF"
        + CAS_HEADER_MARKER
        + b"0123456789ABCDEF"
        + CAS_HEADER_MARKER
        + b"0123456789"
        + CAS_HEADER_MARKER
        + b"END"
    )
    with tempfile.TemporaryDirectory() as tmpdir:
        cas_path = os.path.join(tmpdir, "test2.cas")
        wav_path = os.path.join(tmpdir, "test2.wav")
        with open(cas_path, "wb") as f:
            f.write(multi_cas)
        cas_to_wav(cas_path, wav_path)
        with open(wav_path, "rb") as f:
            gen2 = f.read()
    ok2 = gen2 == expected_wav_multi
    print("[%s] WAV encoding (multi-block pilot leaders)" % ("PASS" if ok2 else "FAIL"))
    if ok2:
        passed += 1
    else:
        failed += 1

    print("%d passed, %d failed" % (passed, failed))
    return failed == 0


def main():
    parser = argparse.ArgumentParser(
        description="Convert MSX .CAS cassette file to .WAV audio."
    )
    parser.add_argument("input", nargs="?", help="input .cas file")
    parser.add_argument("output", nargs="?", help="output .wav file")
    parser.add_argument(
        "--test",
        action="store_true",
        help="run internal self-tests and exit",
    )
    args = parser.parse_args()

    if args.test:
        sys.exit(0 if run_self_tests() else 1)

    if args.input is None or args.output is None:
        parser.error("input and output are required (unless --test is given)")

    cas_to_wav(args.input, args.output)


if __name__ == "__main__":
    main()
